version: "3.8"
services:
  db:
    image: mysql-server:test
    container_name: mysql_server
    restart: unless-stopped
    volumes:
      - mysql-db-volume:/var/lib/mysql
    ports:
      - "3308:3306" #ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'mypassword';
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql_server
    depends_on:
      - db
    ports:
      - "8080:80"
  apache:
    image: apache-php:test
    container_name: apache-php
    restart: unless-stopped
    ports:
      - "8081:80"
  supermarket_tracker:
    image: supermarket_tracker
    container_name: supermarket_tracker
    restart: unless-stopped
volumes:
  mysql-db-volume:
